#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
file="/etc/passwd"
while read -r line; do
	read -a arr <<< $(echo "$line" | cut -d ':' --output-delimiter=' ' -f 1,2,3,4,5,6,7 ;);
	#echo "${arr[@]}";
	echo "The user ${arr[0]} is part of the ${arr[3]} gang, lives in ${arr[5]} and rides ${arr[6]}. ${arr[2]}'s place is protected by the passcode ${arr[1]}, more info about the user here: ${arr[4]}";
done < $file
