#!/usr/bin/env bash
# change ip
cp /etc/hosts ~/hosts.new
sed -i s/^127.*$/"127.0.0.2 localhost"/ ~/hosts.new
#sed -i s/^.*facebook\.com.*$/"8.8.8.8 facebook.com"/ ~/hosts.new
printf "\n8.8.8.8. facebook.com\n" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
