#!/usr/bin/env bash
# change ip
cp /etc/hosts ~/hosts.new
sed -i s/^127.*$/"127.0.0.2\tlocalhost"/ ~/hosts.new
sed -i s/^.*facebook.com$/"8.8.8.8\tfacebook.com"/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
